/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author prana
 */
public class DriverDetails extends javax.swing.JFrame {

    /**
     * Creates new form DriverDetails
     */
    public DriverDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mapSideBar = new javax.swing.JPanel();
        ULogo = new javax.swing.JLabel();
        MyRidesButton = new javax.swing.JButton();
        AcknowledgementsButton = new javax.swing.JButton();
        LogoutButton = new javax.swing.JButton();
        MyProfileButton = new javax.swing.JButton();
        UncleCabsLabel = new javax.swing.JLabel();
        RideDetailsLabel = new javax.swing.JLabel();
        BackButton = new javax.swing.JButton();
        RideLabel = new javax.swing.JLabel();
        ratingLabel = new javax.swing.JLabel();
        cabTypeLabel = new javax.swing.JLabel();
        driverNameLabel = new javax.swing.JLabel();
        cabNumberLabel = new javax.swing.JLabel();
        fareLabel = new javax.swing.JLabel();
        etaLabel = new javax.swing.JLabel();
        driverNameText = new javax.swing.JTextField();
        ratingText = new javax.swing.JTextField();
        cabTypeText = new javax.swing.JTextField();
        cabNumberText = new javax.swing.JTextField();
        fareText = new javax.swing.JTextField();
        etaText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        mapSideBar.setBackground(new java.awt.Color(60, 60, 60));

        ULogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoo.PNG"))); // NOI18N
        ULogo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        MyRidesButton.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 36)); // NOI18N
        MyRidesButton.setText("My Rides");
        MyRidesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MyRidesButtonActionPerformed(evt);
            }
        });

        AcknowledgementsButton.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 28)); // NOI18N
        AcknowledgementsButton.setText("Acknowledgements");
        AcknowledgementsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AcknowledgementsButtonMouseClicked(evt);
            }
        });

        LogoutButton.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 36)); // NOI18N
        LogoutButton.setText("Logout");
        LogoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutButtonMouseClicked(evt);
            }
        });

        MyProfileButton.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 36)); // NOI18N
        MyProfileButton.setText("My Profile");
        MyProfileButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MyProfileButtonMouseClicked(evt);
            }
        });
        MyProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MyProfileButtonActionPerformed(evt);
            }
        });

        UncleCabsLabel.setBackground(new java.awt.Color(0, 0, 0));
        UncleCabsLabel.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 48)); // NOI18N
        UncleCabsLabel.setForeground(new java.awt.Color(255, 255, 255));
        UncleCabsLabel.setText("UNCLE CABS");

        RideDetailsLabel.setBackground(new java.awt.Color(0, 0, 0));
        RideDetailsLabel.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 36)); // NOI18N
        RideDetailsLabel.setForeground(new java.awt.Color(255, 255, 255));
        RideDetailsLabel.setText("Ride Details");

        javax.swing.GroupLayout mapSideBarLayout = new javax.swing.GroupLayout(mapSideBar);
        mapSideBar.setLayout(mapSideBarLayout);
        mapSideBarLayout.setHorizontalGroup(
            mapSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mapSideBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mapSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LogoutButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(UncleCabsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mapSideBarLayout.createSequentialGroup()
                        .addGroup(mapSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(MyRidesButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mapSideBarLayout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(ULogo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(MyProfileButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AcknowledgementsButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mapSideBarLayout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(RideDetailsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        mapSideBarLayout.setVerticalGroup(
            mapSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mapSideBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ULogo, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UncleCabsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MyProfileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MyRidesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AcknowledgementsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RideDetailsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(LogoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        BackButton.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 36)); // NOI18N
        BackButton.setText("Back");
        BackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackButtonMouseClicked(evt);
            }
        });
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        RideLabel.setBackground(new java.awt.Color(0, 0, 0));
        RideLabel.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 48)); // NOI18N
        RideLabel.setForeground(new java.awt.Color(255, 255, 255));
        RideLabel.setText("Ride Details");

        ratingLabel.setBackground(new java.awt.Color(0, 0, 0));
        ratingLabel.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 36)); // NOI18N
        ratingLabel.setForeground(new java.awt.Color(255, 255, 255));
        ratingLabel.setText("Rating");

        cabTypeLabel.setBackground(new java.awt.Color(0, 0, 0));
        cabTypeLabel.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 36)); // NOI18N
        cabTypeLabel.setForeground(new java.awt.Color(255, 255, 255));
        cabTypeLabel.setText("Cab Type");

        driverNameLabel.setBackground(new java.awt.Color(0, 0, 0));
        driverNameLabel.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 36)); // NOI18N
        driverNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        driverNameLabel.setText("Driver Name");

        cabNumberLabel.setBackground(new java.awt.Color(0, 0, 0));
        cabNumberLabel.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 36)); // NOI18N
        cabNumberLabel.setForeground(new java.awt.Color(255, 255, 255));
        cabNumberLabel.setText("Cab Number");

        fareLabel.setBackground(new java.awt.Color(0, 0, 0));
        fareLabel.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 36)); // NOI18N
        fareLabel.setForeground(new java.awt.Color(255, 255, 255));
        fareLabel.setText("Fare");

        etaLabel.setBackground(new java.awt.Color(0, 0, 0));
        etaLabel.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 36)); // NOI18N
        etaLabel.setForeground(new java.awt.Color(255, 255, 255));
        etaLabel.setText("ETA");

        driverNameText.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        driverNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                driverNameTextActionPerformed(evt);
            }
        });

        ratingText.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        ratingText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ratingTextActionPerformed(evt);
            }
        });

        cabTypeText.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        cabTypeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cabTypeTextActionPerformed(evt);
            }
        });

        cabNumberText.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        cabNumberText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cabNumberTextActionPerformed(evt);
            }
        });

        fareText.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        fareText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fareTextActionPerformed(evt);
            }
        });

        etaText.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        etaText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etaTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mapSideBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cabTypeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(driverNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cabNumberLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ratingLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fareLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(RideLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(235, 235, 235)
                        .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ratingText, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(driverNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cabTypeText, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cabNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fareText, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etaText, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mapSideBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RideLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(102, 102, 102)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(driverNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(driverNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ratingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ratingText, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cabTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cabTypeText, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cabNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cabNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fareLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fareText, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(etaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etaText, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1321, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 678, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MyRidesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MyRidesButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MyRidesButtonActionPerformed

    private void AcknowledgementsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AcknowledgementsButtonMouseClicked
        this.setVisible(false) ;
        Acknowledgements ack = new Acknowledgements() ;
        ack.setVisible(true) ;
    }//GEN-LAST:event_AcknowledgementsButtonMouseClicked

    private void LogoutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutButtonMouseClicked
        this.setVisible(false) ;
        Start str = new Start() ;
        str.setVisible(true) ;
    }//GEN-LAST:event_LogoutButtonMouseClicked

    private void MyProfileButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyProfileButtonMouseClicked
        this.setVisible(false) ;
        MyProfile mp = new MyProfile() ;
        mp.setVisible(true) ;
    }//GEN-LAST:event_MyProfileButtonMouseClicked

    private void BackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackButtonMouseClicked
        this.setVisible(false) ;
        map newmap = new map() ;
        newmap.setVisible(true) ;
    }//GEN-LAST:event_BackButtonMouseClicked

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BackButtonActionPerformed

    private void driverNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_driverNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_driverNameTextActionPerformed

    private void ratingTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ratingTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ratingTextActionPerformed

    private void cabTypeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cabTypeTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cabTypeTextActionPerformed

    private void cabNumberTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cabNumberTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cabNumberTextActionPerformed

    private void fareTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fareTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fareTextActionPerformed

    private void etaTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etaTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_etaTextActionPerformed

    private void MyProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MyProfileButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MyProfileButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DriverDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DriverDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DriverDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DriverDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DriverDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AcknowledgementsButton;
    private javax.swing.JButton BackButton;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JButton MyProfileButton;
    private javax.swing.JButton MyRidesButton;
    private javax.swing.JLabel RideDetailsLabel;
    private javax.swing.JLabel RideLabel;
    private javax.swing.JLabel ULogo;
    private javax.swing.JLabel UncleCabsLabel;
    private javax.swing.JLabel cabNumberLabel;
    private javax.swing.JTextField cabNumberText;
    private javax.swing.JLabel cabTypeLabel;
    private javax.swing.JTextField cabTypeText;
    private javax.swing.JLabel driverNameLabel;
    private javax.swing.JTextField driverNameText;
    private javax.swing.JLabel etaLabel;
    private javax.swing.JTextField etaText;
    private javax.swing.JLabel fareLabel;
    private javax.swing.JTextField fareText;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel mapSideBar;
    private javax.swing.JLabel ratingLabel;
    private javax.swing.JTextField ratingText;
    // End of variables declaration//GEN-END:variables
}
